/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kurokami.calendarizador;

/**
 *
 * @author marcos
 */
public class estadisticaCalendarizador extends javax.swing.JPanel {

    /**
     * Creates new form estadisticaCalendarizador
     */
    public estadisticaCalendarizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        estadisticaProceso = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        estadisticaInicio = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        estadisticaTotal = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        estadisticaRestante = new javax.swing.JList<>();
        etiquetaProceso = new javax.swing.JLabel();
        etiquetaInicio = new javax.swing.JLabel();
        etiquetaTotal = new javax.swing.JLabel();
        etiquetaRestante = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        estadisticaFinal = new javax.swing.JList<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estadisticaProceso.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(estadisticaProceso);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 220));

        estadisticaInicio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(estadisticaInicio);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, 220));

        estadisticaTotal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(estadisticaTotal);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 120, 220));

        estadisticaRestante.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(estadisticaRestante);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, 220));

        etiquetaProceso.setText("Prooceso");
        add(etiquetaProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        etiquetaInicio.setText("Inicio");
        add(etiquetaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        etiquetaTotal.setText("Tiempo Total");
        add(etiquetaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        etiquetaRestante.setText("Tiempo Restante");
        add(etiquetaRestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        estadisticaFinal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(estadisticaFinal);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 120, 220));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> estadisticaFinal;
    public static javax.swing.JList<String> estadisticaInicio;
    public static javax.swing.JList<String> estadisticaProceso;
    public static javax.swing.JList<String> estadisticaRestante;
    public static javax.swing.JList<String> estadisticaTotal;
    private javax.swing.JLabel etiquetaInicio;
    private javax.swing.JLabel etiquetaProceso;
    private javax.swing.JLabel etiquetaRestante;
    private javax.swing.JLabel etiquetaTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
