/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kurokami.primerproyectoso;
import kurokami.calendarizador.*;
import malopez.contadorprograma.ContadorPrograma;
import Reloj_Sistema.*;
/**
 *
 * @author marcos
 */
import Reloj_Sistema.ControlReloj_sistema;
public class main extends javax.swing.JFrame {
    
    private Calendarizador calendarizador ;
    private ControlReloj_sistema ControlReloj;
    private estadisticaCalendarizador estadistica;
    private mainCalendarizador principal;
    private ContadorPrograma contador;
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.inicializacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameReloj = new javax.swing.JInternalFrame();
        frameEstadistica = new javax.swing.JInternalFrame();
        frameMain = new javax.swing.JInternalFrame();
        frameContador = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frameReloj.setVisible(true);

        javax.swing.GroupLayout frameRelojLayout = new javax.swing.GroupLayout(frameReloj.getContentPane());
        frameReloj.getContentPane().setLayout(frameRelojLayout);
        frameRelojLayout.setHorizontalGroup(
            frameRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        frameRelojLayout.setVerticalGroup(
            frameRelojLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        getContentPane().add(frameReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 670, 400));

        frameEstadistica.setVisible(true);

        javax.swing.GroupLayout frameEstadisticaLayout = new javax.swing.GroupLayout(frameEstadistica.getContentPane());
        frameEstadistica.getContentPane().setLayout(frameEstadisticaLayout);
        frameEstadisticaLayout.setHorizontalGroup(
            frameEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        frameEstadisticaLayout.setVerticalGroup(
            frameEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        getContentPane().add(frameEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 670, 400));

        frameMain.setVisible(true);

        javax.swing.GroupLayout frameMainLayout = new javax.swing.GroupLayout(frameMain.getContentPane());
        frameMain.getContentPane().setLayout(frameMainLayout);
        frameMainLayout.setHorizontalGroup(
            frameMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        frameMainLayout.setVerticalGroup(
            frameMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        getContentPane().add(frameMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 500, 400));

        frameContador.setVisible(true);

        javax.swing.GroupLayout frameContadorLayout = new javax.swing.GroupLayout(frameContador.getContentPane());
        frameContador.getContentPane().setLayout(frameContadorLayout);
        frameContadorLayout.setHorizontalGroup(
            frameContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        frameContadorLayout.setVerticalGroup(
            frameContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        getContentPane().add(frameContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame frameContador;
    private javax.swing.JInternalFrame frameEstadistica;
    private javax.swing.JInternalFrame frameMain;
    private javax.swing.JInternalFrame frameReloj;
    // End of variables declaration//GEN-END:variables
    public void inicializacion(){
        calendarizador = new Calendarizador();
        calendarizador.start();
        this.setSize(1150, 800);
        contador = new ContadorPrograma();
        this.frameContador.setContentPane(contador);
        this.frameContador.setSize(500, 400);
        this.frameContador.setLocation(0, 0);
        principal = new mainCalendarizador();
        this.frameMain.setContentPane(principal);
        this.frameMain.setSize(500, 400);
        this.frameMain.setLocation(0, 400);
        ControlReloj = new ControlReloj_sistema();
        this.frameReloj.setContentPane(ControlReloj);
        estadistica = new estadisticaCalendarizador();
        this.frameEstadistica.setContentPane(estadistica);
    }
}
